import { FamilyTree, BranchColorDef } from '../types/family';

export const BRANCH_COLORS: BranchColorDef[] = [
  { id: 'emerald', name: 'الزمردي الأندلسي', hex: '#059669', bgClass: 'bg-emerald-500', textClass: 'text-emerald-700', borderClass: 'border-emerald-500' },
  { id: 'navy', name: 'الكحلي الملكي', hex: '#1d4ed8', bgClass: 'bg-blue-600', textClass: 'text-blue-700', borderClass: 'border-blue-600' },
  { id: 'ruby', name: 'العنابي الياقوتي', hex: '#b91c1c', bgClass: 'bg-red-600', textClass: 'text-red-700', borderClass: 'border-red-600' },
  { id: 'amber', name: 'العنبري الذهبي', hex: '#d97706', bgClass: 'bg-amber-500', textClass: 'text-amber-700', borderClass: 'border-amber-500' },
  { id: 'purple', name: 'البنفسجي الفاخر', hex: '#7c3aed', bgClass: 'bg-purple-600', textClass: 'text-purple-700', borderClass: 'border-purple-600' },
  { id: 'cyan', name: 'الفيروزي البراق', hex: '#0891b2', bgClass: 'bg-cyan-600', textClass: 'text-cyan-700', borderClass: 'border-cyan-600' },
  { id: 'rose', name: 'الوردي الأنيق', hex: '#e11d48', bgClass: 'bg-rose-500', textClass: 'text-rose-700', borderClass: 'border-rose-500' },
  { id: 'forest', name: 'الزيتوني العتيق', hex: '#4d7c0f', bgClass: 'bg-lime-700', textClass: 'text-lime-800', borderClass: 'border-lime-700' },
];

export const getBranchColorByIndex = (index: number): BranchColorDef => {
  return BRANCH_COLORS[index % BRANCH_COLORS.length];
};

export const sampleFamilyTree: FamilyTree = {
  id: 'tree-sample-1',
  title: 'شجرة عائلة آل عبد الله المباركة',
  subtitle: 'من الجد المؤسس وصولاً إلى الجيل المعاصر الرابع',
  rootId: 'p-root',
  updatedAt: new Date().toISOString(),
  members: {
    'p-root': {
      id: 'p-root',
      name: 'عبد الله بن عبد العزيز',
      title: 'الجد الأكبر المؤسس',
      gender: 'male',
      parentId: null,
      spouse: 'سارة بنت صالح',
      birthYear: '1920',
      isDeceased: true,
      notes: 'عميد الأسرة ومؤسس التجارة العائلية',
      childrenIds: ['p-branch-1', 'p-branch-2', 'p-branch-3', 'p-branch-4'],
      branchColor: '#059669',
    },
    // Branch 1 - محمد
    'p-branch-1': {
      id: 'p-branch-1',
      name: 'محمد بن عبد الله',
      title: 'أبو فهد',
      gender: 'male',
      parentId: 'p-root',
      spouse: 'نورة بنت حمد',
      birthYear: '1948',
      isDeceased: false,
      childrenIds: ['p-b1-c1', 'p-b1-c2', 'p-b1-c3'],
      branchColor: '#059669',
    },
    'p-b1-c1': {
      id: 'p-b1-c1',
      name: 'فهد بن محمد',
      title: 'أبو تركي',
      gender: 'male',
      parentId: 'p-branch-1',
      spouse: 'هند بنت خالد',
      birthYear: '1975',
      childrenIds: ['p-b1-c1-1', 'p-b1-c1-2'],
      branchColor: '#059669',
    },
    'p-b1-c1-1': {
      id: 'p-b1-c1-1',
      name: 'تركي بن فهد',
      gender: 'male',
      parentId: 'p-b1-c1',
      birthYear: '2002',
      childrenIds: [],
      branchColor: '#059669',
    },
    'p-b1-c1-2': {
      id: 'p-b1-c1-2',
      name: 'سارة بنت فهد',
      gender: 'female',
      parentId: 'p-b1-c1',
      birthYear: '2005',
      childrenIds: [],
      branchColor: '#059669',
    },
    'p-b1-c2': {
      id: 'p-b1-c2',
      name: 'سلطان بن محمد',
      gender: 'male',
      parentId: 'p-branch-1',
      spouse: 'ريم بنت عبد العزيز',
      birthYear: '1979',
      childrenIds: ['p-b1-c2-1'],
      branchColor: '#059669',
    },
    'p-b1-c2-1': {
      id: 'p-b1-c2-1',
      name: 'سعود بن سلطان',
      gender: 'male',
      parentId: 'p-b1-c2',
      birthYear: '2010',
      childrenIds: [],
      branchColor: '#059669',
    },
    'p-b1-c3': {
      id: 'p-b1-c3',
      name: 'منيرة بنت محمد',
      gender: 'female',
      parentId: 'p-branch-1',
      birthYear: '1983',
      childrenIds: [],
      branchColor: '#059669',
    },

    // Branch 2 - عبد الرحمن
    'p-branch-2': {
      id: 'p-branch-2',
      name: 'عبد الرحمن بن عبد الله',
      title: 'أبو إبراهيم',
      gender: 'male',
      parentId: 'p-root',
      spouse: 'لطيفة بنت ناصر',
      birthYear: '1952',
      childrenIds: ['p-b2-c1', 'p-b2-c2'],
      branchColor: '#1d4ed8',
    },
    'p-b2-c1': {
      id: 'p-b2-c1',
      name: 'إبراهيم بن عبد الرحمن',
      title: 'أبو فيصل',
      gender: 'male',
      parentId: 'p-branch-2',
      spouse: 'عبير بنت سليمان',
      birthYear: '1980',
      childrenIds: ['p-b2-c1-1', 'p-b2-c1-2'],
      branchColor: '#1d4ed8',
    },
    'p-b2-c1-1': {
      id: 'p-b2-c1-1',
      name: 'فيصل بن إبراهيم',
      gender: 'male',
      parentId: 'p-b2-c1',
      birthYear: '2008',
      childrenIds: [],
      branchColor: '#1d4ed8',
    },
    'p-b2-c1-2': {
      id: 'p-b2-c1-2',
      name: 'لؤلؤة بنت إبراهيم',
      gender: 'female',
      parentId: 'p-b2-c1',
      birthYear: '2012',
      childrenIds: [],
      branchColor: '#1d4ed8',
    },
    'p-b2-c2': {
      id: 'p-b2-c2',
      name: 'خالد بن عبد الرحمن',
      gender: 'male',
      parentId: 'p-branch-2',
      spouse: 'مها بنت فهد',
      birthYear: '1985',
      childrenIds: ['p-b2-c2-1'],
      branchColor: '#1d4ed8',
    },
    'p-b2-c2-1': {
      id: 'p-b2-c2-1',
      name: 'نايف بن خالد',
      gender: 'male',
      parentId: 'p-b2-c2',
      birthYear: '2015',
      childrenIds: [],
      branchColor: '#1d4ed8',
    },

    // Branch 3 - سليمان
    'p-branch-3': {
      id: 'p-branch-3',
      name: 'سليمان بن عبد الله',
      title: 'أبو أحمد',
      gender: 'male',
      parentId: 'p-root',
      spouse: 'حصة بنت عبد الله',
      birthYear: '1957',
      childrenIds: ['p-b3-c1', 'p-b3-c2'],
      branchColor: '#b91c1c',
    },
    'p-b3-c1': {
      id: 'p-b3-c1',
      name: 'أحمد بن سليمان',
      gender: 'male',
      parentId: 'p-branch-3',
      spouse: 'مشاعل بنت راشد',
      birthYear: '1987',
      childrenIds: ['p-b3-c1-1'],
      branchColor: '#b91c1c',
    },
    'p-b3-c1-1': {
      id: 'p-b3-c1-1',
      name: 'عمر بن أحمد',
      gender: 'male',
      parentId: 'p-b3-c1',
      birthYear: '2018',
      childrenIds: [],
      branchColor: '#b91c1c',
    },
    'p-b3-c2': {
      id: 'p-b3-c2',
      name: 'منى بنت سليمان',
      gender: 'female',
      parentId: 'p-branch-3',
      birthYear: '1990',
      childrenIds: [],
      branchColor: '#b91c1c',
    },

    // Branch 4 - الجوهرة
    'p-branch-4': {
      id: 'p-branch-4',
      name: 'الجوهرة بنت عبد الله',
      title: 'أم عبد العزيز',
      gender: 'female',
      parentId: 'p-root',
      spouse: 'عبد العزيز بن سعود',
      birthYear: '1962',
      childrenIds: ['p-b4-c1', 'p-b4-c2'],
      branchColor: '#d97706',
    },
    'p-b4-c1': {
      id: 'p-b4-c1',
      name: 'سعود بن عبد العزيز',
      gender: 'male',
      parentId: 'p-branch-4',
      birthYear: '1992',
      childrenIds: [],
      branchColor: '#d97706',
    },
    'p-b4-c2': {
      id: 'p-b4-c2',
      name: 'نوف بنت عبد العزيز',
      gender: 'female',
      parentId: 'p-branch-4',
      birthYear: '1996',
      childrenIds: [],
      branchColor: '#d97706',
    },
  },
};

export const createEmptyTree = (rootName: string, title?: string): FamilyTree => {
  const rootId = `root-${Date.now()}`;
  return {
    id: `tree-${Date.now()}`,
    title: title || `شجرة عائلة ${rootName.split(' ')[0] || 'الأسرة'}`,
    subtitle: 'شجرة العائلة الكريمة المباركة',
    rootId,
    updatedAt: new Date().toISOString(),
    members: {
      [rootId]: {
        id: rootId,
        name: rootName,
        title: 'الجد الأكبر المؤسس',
        gender: 'male',
        parentId: null,
        childrenIds: [],
        branchColor: '#059669',
      },
    },
  };
};
